### ISSUE TITLE
Waiting compiler done before server listen

### ISSUE THREAD

**Issue by khanhhaquang** [lependu/fastify-webpack-hmr#23]
Is there a way to `await` Webpack compiler success before start listening fastify server ?

**Comment by lependu** [comment]
Hi! Thanks for checking this out!

Can you give a simple example just to be sure I understand correctly? Which version?

I've never tried this - if I understand it correctly - first thing come into my mind, is to use [after](https://www.fastify.io/docs/latest/Server/#after) or [ready](https://www.fastify.io/docs/latest/Server/#ready) lifecycle hooks of fastify server.

**Comment by khanhhaquang** [comment]
Sorry, I got a misunderstanding, close question now
