### ISSUE TITLE
webpack v5 support 

### ISSUE THREAD

**Issue by gajus** [lependu/fastify-webpack-hmr#49]
Hey,

Can you please indicate in the `README.md` if webpack v5 is supported.

Thank you!

**Comment by lependu** [comment]
Hey @gajus!
Sorry for the late respose. 
I think the [version description](https://github.com/lependu/fastify-webpack-hmr/blame/master/README.md#L18-L26) indicates this clearly. Do you agree? It is not supported, and I have no plan to add that support in the near future. Pull requests are always welcomed! 😉

**Comment by marcbachmann** [comment]
ah, there's an issue for it. Here's a PR #100
